### ISSUE TITLE
Registration form glitches after clicking "Submit"

### ISSUE THREAD

**Issue by aadi1011** [real-tea/SYMBI-TECH-22#3]
Cursor gets stuck and registration form does not clear after submitting it. 

## Form Clearing

https://github.com/real-tea/SYMBI-TECH-22/blob/7bf614099d61bf97f8ce62afff748118bf6970a3/components/RegistrationForm/RegistrationForm.jsx#L50

<code>resetForm({ values: '' });</code> in line 50 can be referenced back to directly initialValues <code>resetForm({ initialValues });</code> from line 38

https://github.com/real-tea/SYMBI-TECH-22/blob/7bf614099d61bf97f8ce62afff748118bf6970a3/components/RegistrationForm/RegistrationForm.jsx#L38

## Cursor stuck glitch
Custom cursor in page is stuck and system cursors activates and not visible in site. Disappears only after closing the JS Prompt. 

![image](https://user-images.githubusercontent.com/62766172/189533644-5bb19ca9-c4d6-48bf-ab18-3f105ced3237.png)

Cursor also disappears when hovering over submit button after first submission.

**Comment by siddxharth** [comment]
Fixed in the latest commit.
