### ISSUE TITLE
Form bug when "submitted"

### ISSUE THREAD

**Issue by aadi1011** [real-tea/SYMBI-TECH-22#4]
In the <i>/register</i> page, when filling the form and submitting it, a window prompt pops up which freezes the custom cursor and the default system cursor is invisible unless hovered over the prompt or browser edges. 

![image](https://user-images.githubusercontent.com/62766172/190214288-e8872184-2198-408e-ae68-d64d2a68c01b.png)

Following which, when the prompt is closed, the form clears as intended although the checkbox of events is still present.
Also, the "Registration Fee" to be payed now shows ₹0.

![image](https://user-images.githubusercontent.com/62766172/190214348-90e8e2ad-5687-4f77-8877-4e1bdfb7ba79.png)

If further any event is removed from the list, the pricing messes up even with a list of events still checked.

![image](https://user-images.githubusercontent.com/62766172/190214409-1fbd2823-4451-466f-b759-bf754670fe2c.png)

This goes for both technical and non-technical events. 

![image](https://user-images.githubusercontent.com/62766172/190214453-c00b4659-00b0-4a4f-bf6d-10d9c91c79be.png)

<i>This fixes when we remove and add one again event each from both categories.</i>

**Comment by siddxharth** [comment]
Yes, it has been fixed in the latest commit.
